const $=id=>document.getElementById(id),SID="pulso90-demo-session-v2",TOK="pulso90-owner-lab-token-v1";let base="",token=localStorage.getItem(TOK)||"";const money=n=>Number(n||0).toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2});
async function runtime(){try{const r=await fetch("runtime-config.json",{cache:"no-store"}),c=await r.json();return String(c.rgs_base||"").replace(/\/$/,"")}catch{return""}}
async function api(path,opt={}){const h={...(opt.headers||{})};if(token)h["x-lab-token"]=token;if(opt.body)h["content-type"]="application/json";const r=await fetch(base+path,{...opt,headers:h});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||"request_failed");return x}
function showApp(on){$("loginPanel").classList.toggle("hide",on);$("app").classList.toggle("hide",!on)}
async function refresh(){const me=await api("/api/internal/me");$("meName").textContent=me.user.name+" · "+me.user.role;$("meBalance").textContent=money(me.state.balance);$("treasury").textContent=money(me.treasury);localStorage.setItem(SID,me.user.demoSessionId);const u=await api("/api/internal/users");$("users").innerHTML=u.users.map(x=>'<div class="item"><b>'+x.name+'</b><div class="mut">'+x.username+' · '+x.role+'</div></div>').join("")||'<div class="mut">Nenhum usuário.</div>';const l=await api("/api/internal/ledger");$("ledger").innerHTML=l.records.slice(0,40).map(x=>'<div class="item"><b>'+x.type+'</b><div class="mut">'+(x.username||x.actor||"")+(x.amount?" · "+money(x.amount):"")+' · '+new Date(x.at).toLocaleString("pt-BR")+'</div></div>').join("")||'<div class="mut">Sem eventos.</div>'}
$("login").onclick=async()=>{try{const x=await api("/api/internal/login",{method:"POST",body:JSON.stringify({username:$("username").value,pin:$("pin").value})});token=x.token;localStorage.setItem(TOK,token);localStorage.setItem(SID,x.user.demoSessionId);showApp(true);await refresh()}catch(e){$("loginMsg").textContent=e.message}};
$("credit").onclick=async()=>{try{const x=await api("/api/internal/wallet/credit",{method:"POST",body:JSON.stringify({amount:Number($("creditAmount").value)})});$("walletMsg").textContent="Crédito adicionado. Saldo: "+money(x.state.balance);await refresh()}catch(e){$("walletMsg").textContent=e.message}};
$("withdraw").onclick=async()=>{try{const x=await api("/api/internal/wallet/withdraw",{method:"POST",body:JSON.stringify({amount:Number($("withdrawAmount").value)})});$("walletMsg").textContent="Saque de teste concluído. Saldo: "+money(x.state.balance);await refresh()}catch(e){$("walletMsg").textContent=e.message}};
$("createUser").onclick=async()=>{try{const x=await api("/api/internal/users",{method:"POST",body:JSON.stringify({name:$("newName").value,username:$("newUser").value,role:$("newRole").value,pin:$("newPin").value})});$("userMsg").textContent="Criado: "+x.user.username;await refresh()}catch(e){$("userMsg").textContent=e.message}};
runtime().then(async b=>{base=b;if(!base){$("loginMsg").textContent="Runtime indisponível";return}if(token){try{showApp(true);await refresh()}catch{token="";localStorage.removeItem(TOK);showApp(false)}}});