const $=id=>document.getElementById(id),SID="pulso90-demo-session-v2",TOK="pulso90-owner-lab-token-v1";let base="",token=localStorage.getItem(TOK)||"";const money=n=>Number(n||0).toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2});
async function runtime(){try{const r=await fetch("runtime-config.json",{cache:"no-store"}),c=await r.json();return String(c.rgs_base||"").replace(/\/$/,"")}catch{return""}}
async function api(path,opt={}){const h={...(opt.headers||{})};if(token)h["x-lab-token"]=token;if(opt.body)h["content-type"]="application/json";const r=await fetch(base+path,{...opt,headers:h});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||"request_failed");return x}
function showApp(on){$("loginPanel").classList.toggle("hide",on);$("app").classList.toggle("hide",!on)}
function renderProviders(rows=[]){$("providerStatus").innerHTML=rows.length?rows.map(p=>'<div class="item"><b>'+p.label+' · '+String(p.environment||"").toUpperCase()+'</b><div class="mut">'+Object.entries(p.secrets||{}).filter(([,v])=>v.configured).map(([k,v])=>k+': '+v.masked).join(' · ')+'</div></div>').join(""):'<div class="mut">Nenhum provedor salvo neste cofre.</div>'}
async function refreshOperator(){const x=await api("/api/internal/operator/config"),o=x.operator||{};$("financialMode").textContent=String(o.financial_mode||"demo").toUpperCase();$("modeSelect").value=o.financial_mode||"demo";$("selectedProvider").value=o.selected_provider||"asaas";$("modePanel").classList.toggle("mode-real",o.financial_mode==="real");$("modeMsg").innerHTML=o.financial_mode==="real"?'<span class="warn">Perfil REAL selecionado.</span> Execução financeira: '+(o.real_execution_enabled?"ATIVA":"BLOQUEADA — "+o.real_execution_reason):'<span class="ok">Perfil DEMO ativo.</span> Créditos, prêmios e saques são simulados.';renderProviders(x.providers||[])}
async function refresh(){const me=await api("/api/internal/me");$("meName").textContent=me.user.name+" · "+me.user.role;$("meBalance").textContent=money(me.state.balance);$("treasury").textContent=money(me.treasury);localStorage.setItem(SID,me.user.demoSessionId);await refreshOperator();const u=await api("/api/internal/users");$("users").innerHTML=u.users.map(x=>'<div class="item"><b>'+x.name+'</b><div class="mut">'+x.username+' · '+x.role+'</div></div>').join("")||'<div class="mut">Nenhum usuário.</div>';const l=await api("/api/internal/ledger");$("ledger").innerHTML=l.records.slice(0,50).map(x=>'<div class="item"><b>'+x.type+'</b><div class="mut">'+(x.username||x.actor||"")+(x.amount?" · "+money(x.amount):"")+' · '+new Date(x.at).toLocaleString("pt-BR")+'</div></div>').join("")||'<div class="mut">Sem eventos.</div>'}
$("login").onclick=async()=>{try{const x=await api("/api/internal/login",{method:"POST",body:JSON.stringify({username:$("username").value,pin:$("pin").value})});token=x.token;localStorage.setItem(TOK,token);localStorage.setItem(SID,x.user.demoSessionId);showApp(true);await refresh()}catch(e){$("loginMsg").textContent=e.message}};
$("saveMode").onclick=async()=>{try{await api("/api/internal/operator/config",{method:"POST",body:JSON.stringify({financial_mode:$("modeSelect").value,selected_provider:$("selectedProvider").value})});await refreshOperator()}catch(e){$("modeMsg").textContent=e.message}};
function providerPayload(){return{provider:$("provider").value,environment:$("providerEnv").value,enabled:true,api_key:$("apiKey").value,access_token:$("accessToken").value,client_id:$("clientId").value,client_secret:$("clientSecret").value,webhook_secret:$("webhookSecret").value,api_base:$("apiBase").value,public_key:$("publicKey").value,account_id:$("accountId").value,wallet_id:$("accountId").value,pix_key:$("pixKey").value,collector_id:$("collectorId").value}}
function clearSecrets(){["apiKey","accessToken","clientId","clientSecret","webhookSecret"].forEach(id=>$(id).value="")}
$("saveProvider").onclick=async()=>{try{const x=await api("/api/internal/operator/provider",{method:"POST",body:JSON.stringify(providerPayload())});clearSecrets();$("providerMsg").innerHTML='<span class="ok">Salvo no cofre local cifrado.</span> O navegador recebe apenas máscara/status.';await refreshOperator()}catch(e){$("providerMsg").textContent=e.message}};
$("deleteProvider").onclick=async()=>{if(!confirm("Remover do cofre as credenciais deste provedor?"))return;try{await api("/api/internal/operator/provider/delete",{method:"POST",body:JSON.stringify({provider:$("provider").value})});$("providerMsg").textContent="Credenciais removidas.";await refreshOperator()}catch(e){$("providerMsg").textContent=e.message}};
$("credit").onclick=async()=>{try{const x=await api("/api/internal/wallet/credit",{method:"POST",body:JSON.stringify({amount:Number($("creditAmount").value)})});$("walletMsg").textContent="Crédito DEMO adicionado. Saldo: "+money(x.state.balance);await refresh()}catch(e){$("walletMsg").textContent=e.message}};
$("withdraw").onclick=async()=>{try{const x=await api("/api/internal/wallet/withdraw",{method:"POST",body:JSON.stringify({amount:Number($("withdrawAmount").value)})});$("walletMsg").textContent="Saque DEMO concluído. Saldo: "+money(x.state.balance);await refresh()}catch(e){$("walletMsg").textContent=e.message}};
$("createUser").onclick=async()=>{try{const x=await api("/api/internal/users",{method:"POST",body:JSON.stringify({name:$("newName").value,username:$("newUser").value,role:$("newRole").value,pin:$("newPin").value})});$("userMsg").textContent="Criado: "+x.user.username;await refresh()}catch(e){$("userMsg").textContent=e.message}};
runtime().then(async b=>{base=b;if(!base){$("loginMsg").textContent="Runtime indisponível";return}if(token){try{showApp(true);await refresh()}catch{token="";localStorage.removeItem(TOK);showApp(false)}}});