const $=id=>document.getElementById(id),SID="pulso90-demo-session-v2";let base="",method="PIX",operatorMode="demo",operator={};
async function runtime(){try{const r=await fetch("runtime-config.json",{cache:"no-store"}),c=await r.json();return String(c.rgs_base||"").replace(/\/$/,"")}catch{return""}}
async function ensureSession(){let sid=localStorage.getItem(SID);if(sid)return sid;if(!base)return"";try{const r=await fetch(base+"/api/lab/session",{method:"POST"}),x=await r.json();if(r.ok&&x.sessionId){localStorage.setItem(SID,x.sessionId);return x.sessionId}}catch{}return""}
async function api(path,opt={}){const sid=await ensureSession(),headers={...(opt.headers||{})};if(sid)headers["x-demo-session"]=sid;if(opt.body)headers["content-type"]="application/json";return fetch(base+path,{...opt,headers})}
function row(x){return '<div class="item"><b>'+(x.type||"evento")+'</b><div class="mut">'+(x.billing_type||"")+' · R$ '+Number(x.value||0).toFixed(2)+' · '+(x.status||"")+'</div></div>'}
function paintMode(){const real=operatorMode==="real";$("walletModeLabel").textContent=real?"CARTEIRA / PERFIL REAL":"CARTEIRA / DEMO";$("walletModeText").textContent=real?"O operador selecionou o perfil REAL. A execução financeira permanece bloqueada até o conector de pagamento e saque estar certificado.":"Ambiente DEMO ativo. Créditos, depósitos, prêmios e saques são simulados.";$("walletActionTitle").textContent=real?"Adicionar saldo — perfil REAL":"Adicionar créditos de teste";$("walletAmountLabel").textContent=real?"Valor solicitado":"Valor de homologação (R$ 5 a R$ 1.000)";$("withdrawStatus").textContent=real?(operator.real_execution_enabled?"Saque REAL habilitado pelo conector certificado.":"Perfil REAL selecionado; saque REAL ainda bloqueado: "+(operator.real_execution_reason||"conector pendente")):"Saque DEMO permanece no circuito fechado do laboratório."}
async function load(){base=await runtime();if(!base){$("providerStatus").textContent="Runtime indisponível.";return}try{const m=await fetch(base+"/api/platform/operator-mode",{cache:"no-store"}),mx=await m.json();operator=mx.operator||{};operatorMode=operator.financial_mode||"demo";paintMode()}catch{}
try{const r=await api("/api/payments/status"),x=await r.json();const realBlocked=operatorMode==="real"&&!operator.real_execution_enabled;$("providerStatus").innerHTML=x.configured?'<span class="ok">'+String(x.provider||"Provedor")+' conectado</span> · '+String(x.environment||""):'Backend pronto, mas o conector financeiro ativo ainda não está configurado.';$("create").disabled=!x.configured||realBlocked;$("create").textContent=operatorMode==="real"?(realBlocked?"Checkout REAL bloqueado":"Gerar checkout REAL"):"Gerar checkout Sandbox"}catch{$("providerStatus").textContent="Não foi possível consultar o backend."}
try{const r=await api("/api/payments/history"),x=await r.json();$("history").innerHTML=x.records?.length?x.records.map(row).join(""):'<div class="mut">Nenhuma movimentação.</div>'}catch{}}
document.querySelectorAll("[data-method]").forEach(b=>b.onclick=()=>{method=b.dataset.method;document.querySelectorAll("[data-method]").forEach(x=>x.classList.toggle("active",x===b))});
$("create").onclick=async()=>{if(operatorMode==="real"&&!operator.real_execution_enabled){$("result").innerHTML='<div class="item warn">Perfil REAL selecionado, mas o conector transacional ainda não foi certificado.</div>';return}const value=Number($("amount").value);$("result").innerHTML='<div class="item">Gerando checkout…</div>';try{const r=await api("/api/payments/create-link",{method:"POST",body:JSON.stringify({value,billingType:method})}),x=await r.json();if(!r.ok)throw new Error(x.error||"Falha");$("result").innerHTML='<div class="item"><b>Checkout criado</b><p class="mut">'+method+' · R$ '+value.toFixed(2)+'</p><a class="btn" style="display:block;text-align:center;text-decoration:none" target="_blank" rel="noopener" href="'+String(x.url).replace(/"/g,"&quot;")+'">Abrir checkout</a></div>';load()}catch(e){$("result").innerHTML='<div class="item warn">'+e.message+'</div>'}};
load();