import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(here,"..");
const data=JSON.parse(fs.readFileSync(path.join(root,"catalog-data.json"),"utf8"));
const providerStatus=JSON.parse(fs.readFileSync(path.join(root,"data","provider-status.json"),"utf8"));
const out=path.join(root,"catalog"),providerOut=path.join(root,"providers");
fs.mkdirSync(out,{recursive:true});fs.mkdirSync(providerOut,{recursive:true});
const providerUrls={pgsoft:"https://www.pgsoft.com/",spribe:"https://spribe.co/",evolution:"https://www.evolution.com/",pragmatic_play:"https://www.pragmaticplay.com/",smartsoft:"https://smartsoftgaming.com/",playngo:"https://www.playngo.com/",games_global:"https://www.gamesglobal.com/"};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
function telemetryScript(event,surface,item,category="",provider=""){const meta=JSON.stringify({event,surface,item,category,provider});return `<script>(()=>{const M=${meta},K="pulso90-anon-v1";let id=localStorage.getItem(K)||"";if(!id){id=(crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)+Date.now().toString(36));localStorage.setItem(K,id)}fetch("../runtime-config.json",{cache:"no-store"}).then(r=>r.json()).then(c=>{const b=String(c.rgs_base||"").replace(/\\/$/,"");if(!b)return;fetch(b+"/api/telemetry/event",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...M,clientId:id,lang:document.documentElement.lang||"pt-BR"}),keepalive:true}).catch(()=>{})}).catch(()=>{})})()</script>`}
const css=`
:root{--bg:#060a08;--p:#0d1712;--line:#294438;--txt:#f3f8f5;--mut:#91a49a;--lime:#b8ff66;--green:#48dc90;--gold:#ffd56b}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 20% 0,#173622,#060a08 40%);color:var(--txt);font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif}a{color:var(--lime);text-decoration:none}.wrap{max-width:1080px;margin:auto;padding:16px}.top{display:flex;align-items:center;gap:10px}.mark{width:40px;height:40px;border-radius:11px;background:var(--lime);color:#07100b;display:grid;place-items:center;font-weight:950}.back{margin-left:auto;font-size:11px}.hero,.panel,.card{border:1px solid var(--line);background:var(--p);border-radius:16px}.hero{margin-top:12px;padding:22px;display:grid;grid-template-columns:150px 1fr;gap:20px;align-items:center}.art{height:150px;border-radius:16px;display:grid;place-items:center;font-size:74px;background:linear-gradient(135deg,#1b3928,#30273e);box-shadow:inset 0 0 0 1px #ffffff10}.ey{font-size:9px;text-transform:uppercase;letter-spacing:.15em;color:var(--lime);font-weight:900}.hero h1{font-size:34px;margin:7px 0}.hero p,.panel p,.card p{font-size:11px;line-height:1.6;color:#a5b5ad}.status{display:inline-block;margin-top:8px;border:1px solid #66552e;color:var(--gold);border-radius:999px;padding:6px 8px;font-size:9px;font-weight:850}.grid{display:grid;grid-template-columns:1.2fr .8fr;gap:10px;margin-top:10px}.panel{padding:15px}.panel h2{margin:0 0 8px;font-size:16px}.tags{display:flex;gap:5px;flex-wrap:wrap}.tag{border:1px solid #2b493b;border-radius:999px;padding:5px 7px;font-size:8px;color:#a9bab1}.cta{display:inline-block;margin:8px 7px 0 0;border:1px solid #3e654f;border-radius:9px;padding:9px 11px;font-size:9px;font-weight:900}.cta.primary{background:var(--lime);color:#07100b;border-color:var(--lime)}.related{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.card{padding:11px}.card b{font-size:11px}.card .ico{font-size:28px}.foot{padding:18px 0;color:#708178;font-size:8px;line-height:1.6}@media(max-width:720px){.hero{grid-template-columns:1fr}.art{height:120px}.grid{grid-template-columns:1fr}.related{grid-template-columns:1fr 1fr}}
`;

function page(g){
 const related=data.games.filter(x=>x.id!==g.id&&(x.provider===g.provider||x.category===g.category)).slice(0,4);
 const canonical="https://idelta775-hash.github.io/pulso90/catalog/"+g.id+".html";
 return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#07100b"><meta name="description" content="${esc(g.title)} no catálogo editorial Pulso 90: provedor, categoria e status de integração."><link rel="canonical" href="${canonical}"><title>${esc(g.title)} — Pulso 90</title><style>${css}</style></head><body><main class="wrap">
 <div class="top"><span class="mark">90</span><div><b>PULSO 90 · CATÁLOGO EDITORIAL</b><div style="font-size:9px;color:#8da096">Descoberta, licenciamento e integração</div></div><a class="back" href="./">← Catálogo</a></div>
 <section class="hero"><div class="art">${g.icon}</div><div><div class="ey">${esc(g.provider)} · ${esc(g.category)}</div><h1>${esc(g.title)}</h1><p>Este título aparece como referência editorial no lobby Pulso 90. A página não incorpora o jogo, não usa assets oficiais do fornecedor e não representa licença ativa.</p><span class="status">${esc(g.status)}</span></div></section>
 <section class="grid"><article class="panel"><h2>Sobre a presença no Pulso 90</h2><p>O objetivo desta página é organizar descoberta, status comercial e caminho de integração. O jogo só poderá se tornar jogável dentro do Pulso 90 por meio de licença/contrato aplicável, certificação exigida e operação compatível com as regras do mercado correspondente.</p><div class="tags">${g.tags.map(t=>'<span class="tag">'+esc(t)+'</span>').join("")}</div><a class="cta primary" href="../games/providers.html">Ver pipeline B2B</a><a class="cta" href="${esc(g.official)}" target="_blank" rel="noopener">Fornecedor oficial ↗</a></article>
 <article class="panel"><h2>Status</h2><p><b>Provedor:</b> ${esc(g.provider)}</p><p><b>Categoria:</b> ${esc(g.category)}</p><p><b>Integração Pulso 90:</b> ainda não ativa</p><p><b>Dinheiro real:</b> não processado nesta página</p><p><b>Assets oficiais:</b> não incorporados sem autorização</p></article></section>
 <section class="panel" style="margin-top:10px"><h2>Relacionados</h2><div class="related">${related.map(x=>'<a class="card" href="'+x.id+'.html"><div class="ico">'+x.icon+'</div><b>'+esc(x.title)+'</b><p>'+esc(x.provider)+' · '+esc(x.category)+'</p></a>').join("")||'<span class="mut">Sem relacionados.</span>'}</div></section>
 <footer class="foot">Marcas e títulos pertencem aos respectivos titulares. Página editorial do Pulso 90; não é uma reprodução do jogo nem uma oferta de aposta.</footer>
 ${telemetryScript("game_open","catalog_page",g.id,g.category,g.provider)}
 </main></body></html>`;
}

for(const g of data.games)fs.writeFileSync(path.join(out,g.id+".html"),page(g),"utf8");
const cards=data.games.map(g=>`<a class="card" href="${g.id}.html"><div class="ico">${g.icon}</div><b>${esc(g.title)}</b><p>${esc(g.provider)} · ${esc(g.category)}</p><span class="status">${esc(g.status)}</span></a>`).join("");
const index=`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Catálogo editorial Pulso 90 de jogos e provedores globais."><link rel="canonical" href="https://idelta775-hash.github.io/pulso90/catalog/"><title>Catálogo Editorial — Pulso 90</title><style>${css}.catalog{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:12px}@media(max-width:900px){.catalog{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.catalog{grid-template-columns:1fr}}</style></head><body><main class="wrap"><div class="top"><span class="mark">90</span><div><b>PULSO 90 · CATÁLOGO</b><div style="font-size:9px;color:#8da096">Editorial + pipeline de integração</div></div><a class="back" href="../">← Home</a></div><section class="hero" style="grid-template-columns:1fr"><div><div class="ey">GLOBAL DISCOVERY</div><h1>Jogos conhecidos. Status transparente.</h1><p>Este catálogo organiza títulos e provedores pesquisados pelo Pulso 90. Nenhum título de terceiro é apresentado como integrado antes de licença e certificação aplicáveis.</p></div></section><section class="catalog">${cards}</section><footer class="foot">Pulso 90 · catálogo editorial. Marcas e jogos pertencem aos respectivos titulares.</footer></main></body></html>`;
fs.writeFileSync(path.join(out,"index.html"),index,"utf8");
function providerPage(p){
 const games=data.games.filter(g=>g.provider===p.name);
 const official=providerUrls[p.id]||"#";
 const cards=games.length?games.map(g=>'<a class="card" href="../catalog/'+g.id+'.html"><div class="ico">'+g.icon+'</div><b>'+esc(g.title)+'</b><p>'+esc(g.category)+'</p></a>').join(""):'<div class="card"><b>Catálogo em prospecção</b><p>O Pulso 90 ainda não selecionou títulos editoriais deste provedor para esta página.</p></div>';
 return '<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="'+esc(p.name)+' no pipeline B2B do Pulso 90."><link rel="canonical" href="https://idelta775-hash.github.io/pulso90/providers/'+p.id+'.html"><title>'+esc(p.name)+' — Pulso 90</title><style>'+css+'</style></head><body><main class="wrap"><div class="top"><span class="mark">90</span><div><b>PULSO 90 · PROVEDOR</b><div style="font-size:9px;color:#8da096">Pipeline B2B e catálogo editorial</div></div><a class="back" href="./">← Provedores</a></div><section class="hero" style="grid-template-columns:1fr"><div><div class="ey">B2B PROVIDER</div><h1>'+esc(p.name)+'</h1><p>Status comercial no Pulso 90: '+esc(p.status)+'. Esta página não representa contrato, licença ativa ou integração técnica concluída.</p><span class="status">'+esc(p.next||"")+'</span></div></section><section class="grid"><article class="panel"><h2>Escopo em análise</h2><div class="tags">'+(p.targets||[]).map(t=>'<span class="tag">'+esc(t)+'</span>').join("")+'</div><a class="cta primary" href="../games/providers.html">Pipeline geral</a><a class="cta" href="'+esc(official)+'" target="_blank" rel="noopener">Site oficial ↗</a></article><article class="panel"><h2>Condição atual</h2><p><b>Integração:</b> não ativa</p><p><b>Assets oficiais:</b> não incorporados sem autorização</p><p><b>Próximo passo:</b> '+esc(p.next||"—")+'</p></article></section><section class="panel" style="margin-top:10px"><h2>Títulos relacionados no catálogo editorial</h2><div class="related">'+cards+'</div></section><footer class="foot">Página editorial/comercial do Pulso 90. Marcas e jogos pertencem aos respectivos titulares.</footer>'+telemetryScript("provider_open","provider_page",p.id,"provider",p.name)+'</main></body></html>';
}
for(const p of providerStatus.providers)fs.writeFileSync(path.join(providerOut,p.id+".html"),providerPage(p),"utf8");
const providerCards=providerStatus.providers.map(p=>'<a class="card" href="'+p.id+'.html"><b>'+esc(p.name)+'</b><p>'+esc((p.targets||[]).join(" · "))+'</p><span class="status">'+esc(p.status)+'</span></a>').join("");
const providerIndex='<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Provedores no pipeline B2B do Pulso 90."><link rel="canonical" href="https://idelta775-hash.github.io/pulso90/providers/"><title>Provedores — Pulso 90</title><style>'+css+'.catalog{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:12px}@media(max-width:720px){.catalog{grid-template-columns:1fr}}</style></head><body><main class="wrap"><div class="top"><span class="mark">90</span><div><b>PULSO 90 · PROVEDORES</b><div style="font-size:9px;color:#8da096">Pipeline B2B sanitizado</div></div><a class="back" href="../">← Home</a></div><section class="hero" style="grid-template-columns:1fr"><div><div class="ey">PROVIDER NETWORK</div><h1>Conteúdo global, integração transparente.</h1><p>Nenhuma marca nesta página é apresentada como parceira contratada antes da formalização correspondente.</p></div></section><section class="catalog">'+providerCards+'</section><footer class="foot">Pulso 90 · status comercial público sanitizado.</footer></main></body></html>';
fs.writeFileSync(path.join(providerOut,"index.html"),providerIndex,"utf8");
const base="https://idelta775-hash.github.io/pulso90/";
const fixed=[["", "hourly","1.0"],["media-kit.html","weekly","0.8"],["games/","weekly","0.9"],["games/providers.html","weekly","0.7"],["games/fairness.html","weekly","0.7"],["games/certification.html","monthly","0.6"],["catalog/","weekly","0.9"],["providers/","weekly","0.8"]];
const urls=[...fixed,...data.games.map(g=>["catalog/"+g.id+".html","weekly","0.7"]),...providerStatus.providers.map(p=>["providers/"+p.id+".html","weekly","0.7"])];
const sitemap='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+urls.map(([u,f,p])=>'  <url><loc>'+base+u+'</loc><changefreq>'+f+'</changefreq><priority>'+p+'</priority></url>').join("\n")+'\n</urlset>\n';
fs.writeFileSync(path.join(root,"sitemap.xml"),sitemap,"utf8");
console.log(JSON.stringify({generated:data.games.length,index:"catalog/index.html",sitemap:urls.length}));
